version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: exact
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://USER:PASSWORD@db:5432/exact
      JWT_SECRET: your_jwt_secret_here
      REFRESH_TOKEN_SECRET: your_refresh_token_secret_here
      API_KEYS: your_api_keys_here
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: yarn start || npm run start
volumes:
  db_data:
