// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sadlfnylsqaeckwaadxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhZGxmbnlsc3FhZWNrd2FhZHhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNDM4NTUsImV4cCI6MjA3MDkxOTg1NX0.RYN6ZhSxxe74OTjdVW_lVyE2_DNxG4SErko7VtHUz1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});